CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT NOT NULL,
  auto_collection TEXT NOT NULL,
  net_term_days INTEGER NOT NULL,
  allow_direct_debit INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  taxability TEXT NOT NULL,
  updated_at INTEGER NOT NULL,
  pii_cleared TEXT NOT NULL,
  resource_version INTEGER NOT NULL,
  deleted INTEGER NOT NULL,
  preferred_currency_code TEXT NOT NULL,
  promotional_credits INTEGER NOT NULL,
  refundable_credits INTEGER NOT NULL,
  excess_payments INTEGER NOT NULL,
  unbilled_charges INTEGER NOT NULL
);

CREATE TABLE subscriptions (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL,
  currency_code TEXT NOT NULL,
  status TEXT NOT NULL,
  billing_period INTEGER NOT NULL,
  billing_period_unit TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  started_at INTEGER NOT NULL,
  activated_at INTEGER NOT NULL,
  current_term_start INTEGER NOT NULL,
  current_term_end INTEGER NOT NULL,
  next_billing_at INTEGER,
  cancelled_at INTEGER,
  cancel_reason_code TEXT,
  remaining_billing_cycles INTEGER,
  due_invoices_count INTEGER NOT NULL,
  due_since INTEGER,
  total_dues INTEGER NOT NULL,
  mrr INTEGER NOT NULL,
  has_scheduled_changes INTEGER NOT NULL,
  has_scheduled_advance_invoices INTEGER NOT NULL,
  deleted INTEGER NOT NULL,
  decommissioned INTEGER NOT NULL,
  resource_version INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  subscription_items TEXT NOT NULL
);

CREATE TABLE invoices (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL,
  subscription_id TEXT NOT NULL,
  recurring INTEGER NOT NULL,
  status TEXT NOT NULL,
  date INTEGER NOT NULL,
  due_date INTEGER NOT NULL,
  paid_at INTEGER,
  net_term_days INTEGER NOT NULL,
  price_type TEXT NOT NULL,
  currency_code TEXT NOT NULL,
  exchange_rate INTEGER NOT NULL,
  sub_total INTEGER NOT NULL,
  tax INTEGER NOT NULL,
  total INTEGER NOT NULL,
  amount_paid INTEGER NOT NULL,
  amount_due INTEGER NOT NULL,
  amount_adjusted INTEGER NOT NULL,
  credits_applied INTEGER NOT NULL,
  write_off_amount INTEGER NOT NULL,
  amount_to_collect INTEGER NOT NULL,
  round_off_amount INTEGER NOT NULL,
  first_invoice INTEGER NOT NULL,
  deleted INTEGER NOT NULL,
  resource_version INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  line_items TEXT NOT NULL,
  linked_payments TEXT NOT NULL
);

CREATE TABLE transactions (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL,
  subscription_id TEXT NOT NULL,
  invoice_id TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  amount INTEGER NOT NULL,
  amount_unused INTEGER NOT NULL,
  currency_code TEXT NOT NULL,
  date INTEGER NOT NULL,
  payment_method TEXT NOT NULL,
  gateway TEXT NOT NULL,
  exchange_rate INTEGER NOT NULL,
  deleted INTEGER NOT NULL,
  resource_version INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE comments (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  notes TEXT NOT NULL,
  added_by TEXT NOT NULL,
  type TEXT NOT NULL,
  created_at INTEGER NOT NULL
);
